# SITE CONFIGURATION
title: Hi, I'm Bruno. # your site title
author: Bruno Koba # You :P
description: > # Meta description of Homepage
  Blog and portfolio website containing articles, photos and code. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brunoaks.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Bruno Koba
  links:
    - https://twitter.com/brunoaks
    #- https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/bruno-koba/
    #- https://plus.google.com/+BenBalter
    - https://github.com/brunoaks
    #- https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About me', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: posts/jp-enoshima.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: brunoaks@gmail.com # email for form submission

twitter_username: brunoaks # replace with your_twitter_username or comment to remove link from footer
github_username:  brunoaks # replace with your_github_username or comment to remove link from footer
instagram_username: kobabr # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: brunoaks # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
