# Site settings
title: Hi, I'm Bruno.
email: brunoaks@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is me in a nutshell.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brunoaks.github.io" # the base hostname & protocol for your site
twitter_username: brunoaks
github_username: brunoaks

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]